
describe('Product Order placed' , function () 
{
    it('Verify types of locator',function ()  {
    

        cy.visit('https://demo.nopcommerce.com/')
        cy.get('#small-searchterms').type("Apple macbook pro 13")
        cy.get('#small-search-box-form > .button-1').click()
        cy.get('.product-box-add-to-cart-button').click()
        cy.get('#product_enteredQuantity_4').clear().type('4')
        cy.get('#add-to-cart-button-4').click()
        cy.get(4000)
        cy.get('.cart-label').click()
        cy.get(4000)
        cy.get('#termsofservice').check()
        cy.get(4000)
        cy.get('#checkout').click()
        cy.get(4000)
        cy.get('.checkout-as-guest-button').click()
        cy.get(4000)
        cy.get('#BillingNewAddress_FirstName').type("Rifat")
        cy.get('#BillingNewAddress_LastName').type("Fatema")
        cy.get('#BillingNewAddress_Email').type("rifatfatema@gmail.com")
        cy.get('#BillingNewAddress_Company').type("Universe")
        cy.get('#BillingNewAddress_CountryId').select("Bangladesh")
        cy.get(2000)
        cy.get('#BillingNewAddress_StateProvinceId').select("Other")
        cy.get('#BillingNewAddress_City').type('Noakhali')
        cy.get('#BillingNewAddress_Address1').type('Selina manjil 1')
        cy.get('#BillingNewAddress_Address2').type('Selina manjil 2')
        cy.get('#BillingNewAddress_ZipPostalCode').type('3800')
        cy.get('#BillingNewAddress_PhoneNumber').type('0174192586')
        cy.get(2000)
        cy.get('#BillingNewAddress_FaxNumber').type('123456')
        cy.get('#billing-buttons-container > .new-address-next-step-button').click()
        cy.get(2000)
        cy.get('#shippingoption_1').check().should('be.checked')
        cy.get('#shipping-method-buttons-container > .button-1').click()
        cy.get('#paymentmethod_1').check().should('be.checked')
        cy.get('#payment-method-buttons-container > .button-1').click()
        cy.get('#CreditCardType').select("Visa")
        cy.get('#CardholderName').type("Rifat fatema")
        cy.get('#CardNumber').type('4111111111111111')
        cy.get('#ExpireMonth').select('02')
        cy.get('#ExpireYear').select('2025')
        cy.get('#CardCode').type('123456')
        cy.get('#payment-info-buttons-container > .button-1').click()
        cy.get('#confirm-order-buttons-container > .button-1').click()
        cy.get('.details-link > a').click()
        cy.get('.pdf-invoice-button').click()

       
        
    })
  })